---
title: "Figure 2 analyses with a more conservative sampling threshold"
output: html_document
date: "2026-01-30"
---

In our main text analyses, we restrict our data to bins that have abundance greater than or equal to 5. In this script, we confirm that our results are robust to even a much more conservative sampling threshold of 20. 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, fig.width = 10)
```


```{r}
library(tidyverse)
library(FAVA)
library(patchwork)
library(broom)

data_pal = PNWColors::pnw_palette("Bay", 3) %>% `names<-`(c("ecogroup", "morphogroup", "species"))

```

```{r}
triton <- data.table::fread("../Data_raw/Data_Triton_v2_Maike_compressed/Triton_Binned_Trimmed.csv")

ecogroup <- data.table::fread("../Data_raw/Data_Triton_v2_Maike_compressed/Ecogroup.csv")
```


# Summarize the data in bins 5 million years wide and 5 degress latitude wide

```{r 5 degree/million year bins}
count_threshold = 20

# Make a table of species counts for each age_bin/lat_bin combo
species_abundances_5my_5deg = triton %>% 
  filter(`Macro.micro` == "Macroperforate") %>%
  transmute(species, 
            age_bin = cut(age, breaks = c(seq(0,60,5), 66)), 
            lat_bin = cut(pal.lat, breaks =c(-76, seq(-70,80,5), 88)), 
            abundance)  %>%
  group_by(age_bin, lat_bin, species) %>%
  summarise(abundance = sum(abundance)) %>%
  pivot_wider(names_from = species, 
              values_from = abundance, 
              values_fill = 0) %>%
  mutate(
    age_lower = as.numeric(str_extract(as.character(age_bin), "-?\\d+\\.?\\d*")),
    age_upper = as.numeric(str_extract(as.character(age_bin), "(?<=,)\\s*-?\\d+\\.?\\d*")), 
    .after = age_bin
  ) %>%
  mutate(
    lat_lower = as.numeric(str_extract(as.character(lat_bin), "-?\\d+\\.?\\d*")),
    lat_upper = as.numeric(str_extract(as.character(lat_bin), "(?<=,)\\s*-?\\d+\\.?\\d*")), 
    .after = lat_bin
  ) %>% 
  mutate(age_bin = forcats::fct_rev(age_bin))

# Remove the 15 age/lat combos with counts < 5
species_abundances_5my_5deg = species_abundances_5my_5deg[rowSums(species_abundances_5my_5deg[,-c(1:6)])>=count_threshold,]

# Normalize rows to generate relative abundances
species_relab_5my_5deg = species_abundances_5my_5deg
species_relab_5my_5deg[,-c(1:6)] = species_abundances_5my_5deg[,-c(1:6)] /rowSums(species_abundances_5my_5deg[,-c(1:6)])



sampling_effort = species_abundances_5my_5deg[,c(1:6)] %>% 
  data.frame %>%
  mutate(total_abundance = rowSums(species_abundances_5my_5deg[,-c(1:6)]),
         age_bin = factor(age_bin, ordered = TRUE, levels = levels(species_abundances_5my_5deg$age_bin) %>% rev))


# Make a table of ecogroup counts for each age_bin/lat_bin combo
ecogroup_abundances_5my_5deg = triton %>% 
  filter(`Macro.micro` == "Macroperforate") %>%
  left_join(ecogroup) %>%
  transmute(ecogroup = `Ecogroup(s)`, 
            age_bin = cut(age, breaks = c(seq(0,60,5), 66)), 
            lat_bin = cut(pal.lat, breaks =c(-76, seq(-70,80,5), 88)), 
            abundance)  %>%
  group_by(age_bin, lat_bin, ecogroup) %>%
  summarise(abundance = sum(abundance)) %>%
  filter(ecogroup !="") %>%
  pivot_wider(names_from = ecogroup, 
              values_from = abundance, 
              values_fill = 0)  %>%
  mutate(
    age_lower = as.numeric(str_extract(as.character(age_bin), "-?\\d+\\.?\\d*")),
    age_upper = as.numeric(str_extract(as.character(age_bin), "(?<=,)\\s*-?\\d+\\.?\\d*")), 
    .after = age_bin
  ) %>%
  mutate(
    lat_lower = as.numeric(str_extract(as.character(lat_bin), "-?\\d+\\.?\\d*")),
    lat_upper = as.numeric(str_extract(as.character(lat_bin), "(?<=,)\\s*-?\\d+\\.?\\d*")), 
    .after = lat_bin
  ) %>% 
  mutate(age_bin = forcats::fct_rev(age_bin))


# Remove the 15 age/lat combos with counts < 5
ecogroup_abundances_5my_5deg = ecogroup_abundances_5my_5deg[rowSums(ecogroup_abundances_5my_5deg[,-c(1:6)])>=count_threshold,]

# Normalize rows to generate relative abundances
ecogroup_relab_5my_5deg = ecogroup_abundances_5my_5deg
ecogroup_relab_5my_5deg[,-c(1:6)] = ecogroup_abundances_5my_5deg[,-c(1:6)] /rowSums(ecogroup_abundances_5my_5deg[,-c(1:6)])




# Make a table of morphogroup counts for each age_bin/lat_bin combo
morphogroup_abundances_5my_5deg = triton %>% 
  filter(`Macro.micro` == "Macroperforate") %>%
  left_join(ecogroup) %>%
  transmute(morphogroup = Morphogroup, 
            age_bin = cut(age, breaks = c(seq(0,60,5), 66)), 
            lat_bin = cut(pal.lat, breaks =c(-76, seq(-70,80,5), 88)), 
            abundance)  %>%
  group_by(age_bin, lat_bin, morphogroup) %>%
  summarise(abundance = sum(abundance)) %>%
  filter(morphogroup !="") %>%
  pivot_wider(names_from = morphogroup, 
              values_from = abundance, 
              values_fill = 0) %>%
  mutate(
    age_lower = as.numeric(str_extract(as.character(age_bin), "-?\\d+\\.?\\d*")),
    age_upper = as.numeric(str_extract(as.character(age_bin), "(?<=,)\\s*-?\\d+\\.?\\d*")), 
    .after = age_bin
  ) %>%
  mutate(
    lat_lower = as.numeric(str_extract(as.character(lat_bin), "-?\\d+\\.?\\d*")),
    lat_upper = as.numeric(str_extract(as.character(lat_bin), "(?<=,)\\s*-?\\d+\\.?\\d*")), 
    .after = lat_bin
  ) %>% 
  mutate(age_bin = forcats::fct_rev(age_bin))


# Remove the 15 age/lat combos with counts < 5
morphogroup_abundances_5my_5deg = morphogroup_abundances_5my_5deg[rowSums(morphogroup_abundances_5my_5deg[,-c(1:6)])>=count_threshold,]

# Normalize rows to generate relative abundances
morphogroup_relab_5my_5deg = morphogroup_abundances_5my_5deg
morphogroup_relab_5my_5deg[,-c(1:6)] = morphogroup_abundances_5my_5deg[,-c(1:6)] /rowSums(morphogroup_abundances_5my_5deg[,-c(1:6)])
```



## SPATIAL HETEROGENEITY


```{r}
species_lat.windows = FAVA::window_fava(relab_matrix = species_relab_5my_5deg,
                                        window_size = 5,
                                        K = 335,
                                        group = "age_bin",
                                        time = "lat_lower")

ecogroup_lat.windows = FAVA::window_fava(relab_matrix = ecogroup_relab_5my_5deg,
                                         window_size = 5,
                                         K = 18,
                                         group = "age_bin",
                                         time = "lat_lower")

morphogroup_lat.windows = FAVA::window_fava(relab_matrix = morphogroup_relab_5my_5deg,
                                            window_size = 5,
                                            K = 19,
                                            group = "age_bin",
                                            time = "lat_lower")

lat.windows_all = morphogroup_lat.windows$window_data %>%
  transmute(age_bin = group,window_index, lat_lower = w1, morphogroup = FAVA, w1, w2, w3, w4, w5) %>% 
  left_join(ecogroup_lat.windows$window_data %>% 
              transmute( age_bin = group, window_index, lat_lower = w1, ecogroup = FAVA, w1, w2, w3, w4, w5)) %>% 
  left_join(species_lat.windows$window_data %>% 
              transmute( age_bin = group,  window_index, lat_lower = w1, species = FAVA, w1, w2, w3, w4, w5)) %>% 
  # pivot_longer(cols = c(w1, w2, w3, w4, w5), values_to = "pal.lat", names_to = "window_bound" ) %>%
  pivot_longer(cols = c(morphogroup, ecogroup, species), 
               names_to = "data", values_to = "FAVA") %>% 
  left_join(species_relab_5my_5deg %>% select(age_bin, age_lower, age_upper, lat_bin, lat_lower, lat_upper) %>%
              distinct) %>% 
  transmute(window_index, w1, w2, w3, w4, w5, lat_bin, lat_lower, lat_upper, 
            age_bin = factor(age_bin, ordered = TRUE, levels = levels(species_abundances_5my_5deg$age_bin) %>% rev), 
            age_lower, age_upper, data, FAVA) 

lat.windows_all = lat.windows_all %>%
  mutate(age_bin_label = paste0("[", - lat.windows_all$age_upper, ", ",
                                - lat.windows_all$age_lower, ")") %>% 
           factor(ordered = TRUE, 
                  levels = unique(paste0("[", - lat.windows_all$age_upper, ", ",
                                         - lat.windows_all$age_lower, ")"))))

discrete_time_pal = viridis::cividis(n = 13, direction = -1) %>% `names<-`(unique(lat.windows_all$age_bin) %>% rev)
```


```{r}

lat_cat_pal = RColorBrewer::brewer.pal(n = 11, name = "Spectral")[c(1,6,9)] %>% `names<-`(c("Southern", "Equatorial", "Northern"))

t = 30
latcat = lat.windows_all %>%
  mutate(lat_cat = ifelse(w1 < -t, "Southern", 
                          ifelse(w5>t, "Northern", "Equatorial")) %>%
           factor(ordered = TRUE, levels = c("Southern", "Equatorial", "Northern")),
         age_cat = cut(age_upper, c(0, 20, 40, 66)) %>% factor(ordered = TRUE) %>% forcats::fct_rev()) %>% 
  left_join(data.frame(age_cat = c("(0,20]", "(20,40]", "(40,66]"), 
                       age_cat_label = c("[-20,0)", "[-40,-20)", "[-66,-40)") %>% factor(ordered = TRUE, levels = c("[-20,0)", "[-40,-20)", "[-66,-40)") %>% rev)))

table(latcat$lat_cat)
table(latcat$age_cat)

```


```{r}
design <- matrix(c(1, 2, 3, 4, 5,
                   6, 7, 8, 9, NA,
                   10, 11, 12, 13, NA), byrow=T, ncol = 5)

lat_spatial_gradient_2 = ggplot(lat.windows_all %>% 
                                  pivot_longer(cols = c(w1, w5), values_to = "pal.lat", names_to = "window_bound" )  %>% 
                                  mutate(age_bin = forcats::fct_rev(age_bin)), 
                                aes(x = pal.lat, y = FAVA, 
                                    color = data, 
                                    group = paste0(window_index, age_bin, data, FAVA))) + 
  geom_vline(xintercept = 0, color ="grey", linewidth = 1.5) +
  geom_vline(xintercept = c(-30, 30), color ="grey", linewidth = 0.5) +
  geom_line(linewidth = 1, alpha=0.5) + 
  theme_bw() + scale_color_manual(values = data_pal, name = "Data") + 
  ggh4x::facet_manual(~ age_bin_label, design = design) +
  guides(color = guide_legend(override.aes = list(alpha = 1))) +
  theme(legend.position = c(0.92, 0.18), #legend.title = element_blank(),
        legend.background = element_blank(), panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank()) + 
  geom_point(data = lat.windows_all%>% 
               mutate(age_bin = forcats::fct_rev(age_bin))%>% 
               pivot_longer(cols = c(w1, w5), values_to = "pal.lat", names_to = "window_bound" )  %>%
               filter(window_bound == "w1"), size = 0.6, alpha = 0.8)+ 
  geom_line(aes(group = data), data = lat.windows_all%>% 
              mutate(age_bin = forcats::fct_rev(age_bin))%>% 
              pivot_longer(cols = c(w1, w5), values_to = "pal.lat", names_to = "window_bound" )  %>%
              filter(window_bound == "w1"), linewidth = 0.5, alpha = 0.8) + 
  xlab("Paleolatitude")

box_data_2 = ggplot(latcat, aes(x = lat_cat, y = FAVA, fill = data, color = data)) + geom_boxplot(alpha=0.3, outlier.alpha = 1) + 
  # ggpubr::stat_compare_means(comparisons = list(c("Southern", "Equatorial"), 
  #                                               c("Equatorial", "Northern"), 
  #                                               c("Southern", "Northern"))) +
  scale_fill_manual(values = data_pal, name = "Data") + 
  scale_color_manual(values = data_pal, name = "Data") + 
  theme_bw() + 
  facet_wrap(~age_cat_label, ncol = 1) + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle = -0,vjust = 0),
        legend.position = c(0.55, 0.52))  +
  ggpubr::stat_compare_means(comparisons = list(c("Southern", "Equatorial"),
                                                c("Equatorial", "Northern"), 
                                                c("Southern", "Northern")), 
                             aes(label = ..p.signif..),
                             label.y = c(0.2, 0.25, 0.32)) + 
  ylim(0,0.36)

panels2 = wrap_plots(lat_spatial_gradient_2, box_data_2+ theme(legend.position = "none"), widths = c(3,1)) + plot_annotation(tag_levels = "A") & ylab("Spatial FAVA")
panels2

# ggsave("../Figures/lat_space_gradient_20_sample_threshold.png", panels2, width = 30, height = 18, scale = 0.3)
```

## statistics
```{r}
wilcox.test(filter(latcat, age_cat_label == "[-20,0)", lat_cat == "Equatorial")$FAVA, 
            filter(latcat, age_cat_label == "[-20,0)", lat_cat == "Southern")$FAVA,
            alternative = "less")

wilcox.test(filter(latcat, age_cat_label == "[-20,0)", lat_cat == "Equatorial")$FAVA, 
            filter(latcat, age_cat_label == "[-20,0)", lat_cat == "Northern")$FAVA,
            alternative = "less")

wilcox.test(filter(latcat, age_cat_label == "[-66,-40)", lat_cat == "Equatorial")$FAVA, 
            filter(latcat, age_cat_label == "[-66,-40)", lat_cat == "Southern")$FAVA,
            alternative = "greater")

wilcox.test(filter(latcat, age_cat_label == "[-66,-40)", lat_cat == "Equatorial")$FAVA, 
            filter(latcat, age_cat_label == "[-66,-40)", lat_cat == "Northern")$FAVA,
            alternative = "greater")


```


